version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: /usr/src
     steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            npm run build:ci
